---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/moverz20180615/public_html/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R home $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R model $DEPLOYPATH
    - /bin/cp -R new-sample-upload-form-movers $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp -R upload-report-form-movers $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH