<?php

function stateLinkFor($stateAbbreviation){
$properStateLinks = array(
    "AL" => "http://arc-sos.state.al.us/CGI/CORPNAME.MBR/INPUT",
    "AK" => "http://commerce.alaska.gov/CBP/Main/CBPLSearch.aspx?mode=Corp",
    "AZ" => "http://www.azsos.gov/scripts/TNT_Search_engine.dll",
    "AR" => "http://www.sos.arkansas.gov/corps/search_all.php",
    "CA" => "http://kepler.sos.ca.gov/cbs.aspx",
    "CO" => "http://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do",
    "CT" => "http://www.concord-sots.ct.gov/CONCORD/online?eid=99&sn=InquiryServlet",
    "DE" => "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
    "FL" => "http://www.sunbiz.org/corinam.html",
    "GA" => "https://ecorp.sos.ga.gov/BusinessSearch",
    "HI" => "http://hbe.ehawaii.gov/documents/search.html",
    "ID" => "https://www.accessidaho.org/public/sos/corp/search.html",
    "IL" => "https://www.ilsos.gov/corporatellc/CorporateLlcController",
    "IN" => "https://bsd.sos.in.gov/publicbusinesssearch",
    "IA" => "http://sos.iowa.gov/search/business/search.aspx",
    "KS" => "https://www.kansas.gov/bess/flow/main?execution=e1s1",
    "KY" => "https://app.sos.ky.gov/ftsearch/",
    "LA" => "http://coraweb.sos.la.gov/commercialsearch/commercialsearch.aspx",
    "ME" => "https://icrs.informe.org/nei-sos-icrs/ICRS?MainPage=x",
    "MD" => "http://sdat.resiusa.org/ucc-charter/Pages/CharterSearch/default.aspx",
    "MA" => "http://corp.sec.state.ma.us/corp/corpsearch/corpsearchinput.asp",
    "MI" => "http://www.dleg.state.mi.us/bcs_corp/sr_corp.asp",
    "MN" => "http://mblsportal.sos.state.mn.us/",
    "MS" => "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx?#clear=1",
    "MO" => "https://www.sos.mo.gov/BusinessEntity/soskb/csearch.asp",
    "MT" => "https://app.mt.gov/bes",
    "NE" => "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
    "NV" => "http://nvsos.gov/sosentitysearch/corpsearch.aspx",
    "NH" => "https://www.sos.nh.gov/corporate/soskb/csearch.asp",
    "NJ" => "https://www.njportal.com/DOR/businessrecords/",
    "NM" => "https://portal.sos.state.nm.us/BFS/online/CorporationBusinessSearch",
    "NY" => "https://appext20.dos.ny.gov/corp_public/corpsearch.entity_search_entry",
    "NC" => "http://www.secretary.state.nc.us/corporations/csearch.aspx",
    "ND" => "https://secure.apps.state.nd.us/sc/busnsrch/busnSearch.htm",
    "OH" => "https://www5.sos.state.oh.us:8443/ords/f?p=100:1:0::NO",
    "OK" => "https://www.sos.ok.gov/business/corp/records.aspx",
    "OR" => "http://egov.sos.state.or.us/br/pkg_web_name_srch_inq.login",
    "PA" => "https://www.corporations.pa.gov/Search/CorpSearch",
    "RI" => "http://ucc.state.ri.us/CorpSearch/CorpSearchEntityList.asp?ReadFromDB=True&UpdateAllowed=",
    "SC" => "http://www.sos.sc.gov/Search%20Business%20Filings",
    "SD" => "http://sdsos.gov/Business/Search.aspx",
    "TN" => "http://tnbear.tn.gov/ECommerce/FilingSearch.aspx",
    "TX" => "https://ourcpa.cpa.state.tx.us/coa/Index.html",
    "UT" => "https://secure.utah.gov/bes/action",
    "VT" => "http://www.sec.state.vt.us/seek/keysrch.htm",
    "VA" => "https://cisiweb.scc.virginia.gov/z_container.aspx",
    "WA" => "https://fortress.wa.gov/dol/dolprod/bpdLicenseQuery/Default.aspx",
    "WV" => "http://apps.sos.wv.gov/business/corporations/",
    "WI" => "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
    "WY" => "https://wyobiz.wy.gov/Business/FilingSearch.aspx",
    "DC" => "http://lsdbe.dslbd.dc.gov/public/certification/search.aspx?olbdNav=|31105|",
    //various canadian abbreviations if we need them in the future
    "AB" => "",
    "BC" => "",
    "MB" => "",
    "NB" => "",
    "NL" => "",
    "NT" => "",
    "NS" => "",
    "ON" => "",
    "PE" => "",
    "QC" => "",
    "SK" => "",
    "YT" => "",
    "NU" => ""
);
    return $properStateLinks[$stateAbbreviation];
}

?>